### ISSUE TITLE
获取电影基本信息的接口一直返回500错误

### ISSUE THREAD

**Issue by Anbool** [xhboke/douban#11]
使用的2.0.2版本，测试访问这个接口：http://127.0.0.1:8000/subject/25845392一直返回500错误，PHP版本是7.4

**Comment by xhboke** [comment]
我刚刚下载了2.0.2，能正常返回结果，

访问下其他编号，试试能返回结果吗？

**Comment by Anbool** [comment]
> 我刚刚下载了2.0.2，能正常返回结果，
> 
> 访问下其他编号，试试能返回结果吗？

报错信息是这个文件：MovieInfo.php的510行

**Comment by xhboke** [comment]
本意是想在豆瓣电影没有给播放链接时，从外部搜索获取满足播放的需求。
那你可以把这个函数的参数值设为`$is_play_url = False` 
https://github.com/xhboke/douban/blob/e9a1ca54b314b1547f08026964aa89a28bcd5486/extend/DouBanLib/MovieInfo.php#L38

**Comment by Anbool** [comment]
> 本意是想在豆瓣电影没有给播放链接时，从外部搜索获取满足播放的需求。 那你可以把这个函数的参数值设为`$isAccurate = False` 就可以避免调用这个函数。
> 
> https://github.com/xhboke/douban/blob/e9a1ca54b314b1547f08026964aa89a28bcd5486/extend/DouBanLib/MovieInfo.php#L38
> 
> 
> 同时这里改为`return json($obj->getAll(false, true));`
> https://github.com/xhboke/douban/blob/e9a1ca54b314b1547f08026964aa89a28bcd5486/application/movie/controller/Info.php#L20

谢谢，我重新试试
