### ISSUE TITLE
小部分数据会返回空

### ISSUE THREAD

**Issue by IceDream1024** [xhboke/douban#21]
# 测试id
> [在豆瓣详情页都是可以访问到数据的](https://douban.com/subject/35295695)

- 35559753
- 35559425
- 35094465
- 35230639

<img width="777" alt="image" src="https://user-images.githubusercontent.com/41316193/162654621-d4a5b3c4-df2c-497e-8e77-05523fb6aee5.png">

**Comment by xhboke** [comment]
这些编号似乎都重定向到了另外一个编号。

**Comment by xhboke** [comment]
设置下 `curl` 请求重定向即可
