### ISSUE TITLE
怎么安装使用呢？

### ISSUE THREAD

**Issue by cnstephen** [xhboke/douban#3]
怎么安装使用呢？

**Comment by xhboke** [comment]
需要一些PHP基本知识。

--------------原始邮件--------------
发件人："cnstephen ***@***.***&gt;;
发送时间：2021年3月20日(星期六) 晚上8:53
收件人："xhboke/douban" ***@***.***&gt;;
抄送："Subscribed ***@***.***&gt;;
主题：[xhboke/douban] 怎么安装使用呢？ (#3)
-----------------------------------

 

 
怎么安装使用呢？

**Comment by cnstephen** [comment]
> 需要一些PHP基本知识。
> […](#)
> --------------原始邮件-------------- 发件人："cnstephen ***@***.***&gt;; 发送时间：2021年3月20日(星期六) 晚上8:53 收件人："xhboke/douban" ***@***.***&gt;; 抄送："Subscribed ***@***.***&gt;; 主题：[xhboke/douban] 怎么安装使用呢？ (#3) ----------------------------------- 怎么安装使用呢？ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

下载之后直接放在网站里面。空白页面。需要对接数据库吗？起床后试一下。

**Comment by cnstephen** [comment]
新的上传到服务器，index.php空白
可以来个实例吗，谢谢

**Comment by xhboke** [comment]
api.xhboke.com/doc/movie

--------------原始邮件--------------
发件人："cnstephen ***@***.***&gt;;
发送时间：2021年3月21日(星期天) 上午9:21
收件人："xhboke/douban" ***@***.***&gt;;
抄送："小小航 ***@***.***&gt;;"Comment ***@***.***&gt;;
主题：Re: [xhboke/douban] 怎么安装使用呢？ (#3)
-----------------------------------

 

 
新的上传到服务器，index.php空白
 可以来个实例吗，谢谢

**Comment by Lil-C0der** [comment]
用豆瓣的海报图片好像会报403？请问你是怎么解决的？

**Comment by Lil-C0der** [comment]
> 需要一些PHP基本知识。
> […](#)
> --------------原始邮件-------------- 发件人："cnstephen ***@***.***&gt;; 发送时间：2021年3月20日(星期六) 晚上8:53 收件人："xhboke/douban" ***@***.***&gt;; 抄送："Subscribed ***@***.***&gt;; 主题：[xhboke/douban] 怎么安装使用呢？ (#3) ----------------------------------- 怎么安装使用呢？ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

用豆瓣的海报图片好像会报403？请问你是怎么解决的？

**Comment by xhboke** [comment]
一种是：Html加上meta标签 referrer never（我的做法）
或者用后端接受处理图片（对性能要求高）

--------------原始邮件--------------
发件人："Lil-C0der ***@***.***&gt;;
发送时间：2021年3月21日(星期天) 晚上9:34
收件人："xhboke/douban" ***@***.***&gt;;
抄送："小小航 ***@***.***&gt;;"Comment ***@***.***&gt;;
主题：Re: [xhboke/douban] 怎么安装使用呢？ (#3)
-----------------------------------

 

 
用豆瓣的海报图片好像会报403？请问你是怎么解决的？
