### ISSUE TITLE
ChineseName  电影的可以了 电视剧的还是不行

### ISSUE THREAD

**Issue by iowong** [xhboke/douban#7]
![微信截图_20210702184220](https://user-images.githubusercontent.com/74191259/124263218-8edd9c00-db65-11eb-9dfd-e7f66436f428.png)

id=35231321

**Comment by xhboke** [comment]
直接从标题获取中文名称。
`$this->ChineseName = trim(str_replace(array("\n", "\r","(豆瓣)"), "", $this->preg('#<title>([\s\S]*?)<\/title>#', $this->data, 1)[0]));`
