### ISSUE TITLE
ChineseName获取的名称不完整

### ISSUE THREAD

**Issue by iowong** [xhboke/douban#8]
ChineseName获取的名称不完整 
希望增加 制片国家/地区

**Comment by xhboke** [comment]
能否提供下哪部影片的`ChineseName`获取不完整

**Comment by iowong** [comment]
> 能否提供下哪部影片的`ChineseName`获取不完整
好像只有部分获取不完整
![微信截图_20210901170303](https://user-images.githubusercontent.com/74191259/131643725-7feb0308-fc45-4c6d-9705-a205329e281f.png)
![微信截图_20210901170126](https://user-images.githubusercontent.com/74191259/131643734-caa6b892-2df0-411a-86d2-52892777eb46.png)
